reviews:
  profile: chill
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["next-update"]
  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true
