name: Essence
version: '${project.version}'
main: net.lewmc.essence.Essence
api-version: 1.20
author: LewMC
description: Stress-free server utilities.
website: https://lewmc.net/plugin/essence
load: STARTUP
folia-supported: true
softdepend: ["Vault","PlaceholderAPI"]
permissions:
  essence.*:
    description: Access to all essence commands.
    default: op
    children:
      essence.gamemode.*: true
      essence.inventory.*: true
      essence.teleport.*: true
      essence.warp.*: true
      essence.stats.*: true
      essence.stats.other.*: true
      essence.home.*: true
      essence.economy.*: true
      essence.chat.*: true
      essence.team.*: true
      essence.spawn.*: true
      essence.kits.*: true
      essence.environment.*: true
      essence.rules: true
  essence.gamemode.*:
    description: Allows players to switch to any gamemode.
    default: op
    children:
      essence.gamemode.creative: true
      essence.gamemode.survival: true
      essence.gamemode.adventure: true
      essence.gamemode.spectator: true
      essence.gamemode.other: true
  essence.gamemode.creative:
    description: Allows players to switch to creative gamemode.
  essence.gamemode.survival:
    description: Allows players to switch to survival gamemode.
  essence.gamemode.adventure:
    description: Allows players to switch to adventure gamemode.
  essence.gamemode.spectator:
    description: Allows players to switch to spectator gamemode.
  essence.gamemode.other:
    description: Allows you to change other player's gamemodes. You must also have the specific gamemode permission.
  essence.inventory.*:
    description: Allows players to access inventory commands.
    default: op
    children:
      essence.inventory.anvil: true
      essence.inventory.cartography: true
      essence.inventory.craft: true
      essence.inventory.enderchest: true
      essence.inventory.grindstone: true
      essence.inventory.loom: true
      essence.inventory.smithing: true
      essence.inventory.stonecutter: true
      essence.inventory.trash: true
  essence.inventory.anvil:
    description: Allows players to open an anvil when no anvil is present.
  essence.inventory.cartography:
    description: Allows players to open a cartography table when no cartography table is present.
  essence.inventory.craft:
    description: Allows players to open a crafting table when no crafting table is present.
  essence.inventory.enderchest:
    description: Allows players to open their ender chest.
  essence.inventory.grindstone:
    description: Allows players to open a grindstone when no grindstone is present.
  essence.inventory.loom:
    description: Allows players to open a loom when no loom is present.
  essence.inventory.smithing:
    description: Allows players to open a smithing table when no smithing table is present.
  essence.inventory.stonecutter:
    description: Allows players to open a stonecutter when no stonecutter is present.
  essence.inventory.trash:
    description: Allows players to open the disposal menu.
  essence.teleport.*:
    description: Allows players to teleport.
    default: op
    children:
      essence.teleport.coord: true
      essence.teleport.player: true
      essence.teleport.offline: true
      essence.teleport.back: true
      essence.teleport.back.other: true
      essence.teleport.random: true
      essence.teleport.other: true
      essence.teleport.request.*: true
  essence.teleport.coord:
    description: Allows players to teleport to coordinates.
  essence.teleport.player:
    description: Allows players to teleport to a player.
  essence.teleport.offline:
    description: Allows players to teleport to an offline player.
  essence.teleport.back:
    description: Go back to your last location before teleporting.
  essence.teleport.back.other:
    description: Teleport another player back to their last location.
  essence.teleport.random:
    description: Teleport to a random location.
  essence.teleport.other:
    description: Teleport another player.
  essence.teleport.request.*:
    description: Allow players to request to teleport.
    default: op
    children:
      essence.teleport.request.send: true
      essence.teleport.request.here: true
      essence.teleport.request.accept: true
      essence.teleport.request.deny: true
      essence.teleport.request.toggle: true
      essence.teleport.request.cancel: true
  essence.teleport.request.send:
    description: Request to teleport to a player.
  essence.teleport.request.here:
    description: Request a player teleport to you.
  essence.teleport.request.accept:
    description: Accept a teleport request.
  essence.teleport.request.deny:
    description: Deny a teleport request.
  essence.teleport.request.toggle:
    description: Toggle receiving teleport requests.
  essence.teleport.request.cancel:
    description: Cancel a teleport request.
  essence.warp.*:
    description: Allows players to use and manage warps.
    default: op
    children:
      essence.warp.use: true
      essence.warp.list: true
      essence.warp.create: true
      essence.warp.delete: true
  essence.warp.use:
    description: Allows players to warp.
  essence.warp.list:
    description: Allows players view warps.
  essence.warp.create:
    description: Allows players to create warps.
  essence.warp.delete:
    description: Allows players to delete warps.
  essence.stats.*:
    description: Allows players to manage their stats such as health and hunger.
    default: op
    children:
      essence.stats.heal: true
      essence.stats.feed: true
      essence.stats.repair: true
      essence.stats.fly: true
      essence.stats.speed: true
  essence.stats.heal:
    description: Allows you to heal yourself.
  essence.stats.feed:
    description: Allows you to feed yourself.
  essence.stats.repair:
    description: Allows you to repair items.
  essence.stats.fly:
    description: Allows you to fly.
  essence.stats.speed:
    description: Allows you to set your speed.
  essence.stats.other.*:
    description: Allows players to manage other player's stats such as health and hunger.
    default: op
    children:
      essence.stats.heal.other: true
      essence.stats.feed.other: true
      essence.stats.fly.other: true
      essence.stats.speed.other: true
  essence.stats.heal.other:
    description: Allows you to heal other players.
  essence.stats.feed.other:
    description: Allows you to feed other players.
  essence.stats.fly.other:
    description: Allows you to let other players fly.
  essence.stats.speed.other:
    description: Allows you to set other player's speed.
  essence.home.*:
    description: Allows players to use the home system.
    default: op
    children:
      essence.home.list: true
      essence.home.use: true
      essence.home.set: true
      essence.home.delete: true
      essence.home.team.list: true
      essence.home.team.use: true
      essence.home.team.set: true
      essence.home.team.delete: true
  essence.home.list:
    description: View a list of homes.
  essence.home.use:
    description: Allows players to teleport to your homes.
  essence.home.set:
    description: Allows players to set homes.
  essence.home.delete:
    description: Allows players to delete homes.
  essence.home.team.list:
    description: View a list of team homes.
  essence.home.team.use:
    description: Allows players to teleport to team homes.
  essence.home.team.set:
    description: Allows players to set team homes.
  essence.home.team.delete:
    description: Allows players to delete team homes.
  essence.chat.*:
    description: Allows players to use all chat commands.
    default: op
    children:
      essence.chat.broadcast: true
      essence.chat.msg: true
      essence.chat.reply: true
      essence.chat.nick: true
      essence.chat.nick.*: true
  essence.chat.broadcast:
    description: Allows players to broadcast a message to chat.
  essence.chat.msg:
    description: Allows players to privately message.
  essence.chat.reply:
    description: Allows players to change display names.
  essence.chat.nick.*:
    default: op
    children:
      essence.chat.nick.self: true
      essence.chat.nick.other: true
  essence.chat.nick.self:
    description: Allows players to change their display names.
  essence.chat.nick.other:
    description: Allows players to change other player's display names.
  essence.economy.*:
    description: Allows players to access all economy commands.
    default: op
    children:
      essence.economy.pay: true
      essence.economy.balance: true
  essence.economy.pay:
    description: Use /pay command.
  essence.economy.balance:
    description: Use /balance command.
  essence.team.*:
    description: Allows players to access all teams commands.
    default: op
    children:
      essence.team.join: true
      essence.team.create: true
      essence.team.manage: true
      essence.team.list: true
  essence.team.join:
    description: Join a team.
  essence.team.create:
    description: Create a team.
  essence.team.manage:
    description: Manage any teams they are the leader of.
  essence.team.list:
    description: View team information.
  essence.spawn.*:
    description: Allows players to access all spawn commands.
    default: op
    children:
      essence.spawn: true
      essence.spawn.set: true
      essence.spawn.other: true
  essence.spawn.set:
    description: Set the spawn.
  essence.spawn:
    default: not op
    description: Teleport to spawn.
  essence.spawn.other:
    description: Teleport to other world's spawns.
  essence.kits.*:
    description: Allows players to access all kit commands.
    default: op
    children:
      essence.kits.all: true
  essence.kits.all:
    description: Allows players to access all kits.
  essence.admin.*:
    description: Allows players to access admin commands.
    default: op
    children:
      essence.admin.seen: true
      essence.admin.info: true
      essence.admin.info.viewip: true
      essence.admin.reload: true
      essence.admin.restore: true
      essence.admin.import: true
      essence.admin.invisible: true
      essence.admin.updates: true
  essence.admin.seen:
    description: Allows players to see when the player was last online.
  essence.admin.info:
    description: Allows players to see information about the player.
  essence.admin.info.viewip:
    description: Allows players to see other player's IP addresses.
  essence.admin.reload:
    description: Allows players to reload Essence.
  essence.admin.restore:
    description: Allows players to restore Essence's files.
  essence.admin.import:
    description: Allows players to reload Essence.
  essence.admin.invisible:
    description: Toggles invisibility.
  essence.admin.updates:
    description: Toggles invisibility.
  essence.bypass.*:
    description: Allows bypassing of various limits.
    default: false
    children:
      essence.bypass.teleportcooldown: true
      essence.bypass.teleportdelay: true
      essence.bypass.maxkitclaims: true
  essence.bypass.teleportcooldown:
    description: Allows bypassing the teleportation cooldown.
  essence.bypass.teleportdelay:
    description: Allows bypassing the teleportation delay.
  essence.bypass.extendedteleporttoggle:
    description: Allows bypassing the extended teleport toggles.
  essence.bypass.maxkitclaims:
    description: Allows bypassing the maximum number of kit redemptions.
  essence.rules:
    description: Allows players to view the server rules.
  essence.environment.*:
    description: Allows changing environmental variables.
    default: op
    children:
      essence.environment.time: true
      essence.environment.weather: true
      essence.environment.ptime: true
      essence.environment.pweather: true
  essence.environment.time:
    description: Allows changing the time.
  essence.environment.weather:
    description: Allows changing the weather.
  essence.environment.ptime:
    description: Allows changing your player time.
  essence.environment.pweather:
    description: Allows changing your player weather.