name: Essence
version: '${project.version}'
main: net.lewmc.essence.Essence
api-version: 1.20
author: LewMC
description: An Essentials alternative for LewMC servers.
website: https://lewmc.net
load: POSTWORLD
folia-supported: true
softdepend: ["Vault","PlaceholderAPI"]
depend: ["Foundry"]
commands:
  essence:
    description: Main command
    usage: /<command> [help] [topic] [chapter]
    aliases: ['es','ess']
  gamemode:
    description: Change your gamemode.
    usage: /<command> <mode>
    aliases: ['gm']
    permission: essence.gamemode.*
  gms:
    description: Switch to survival mode.
    usage: /<command>
    aliases: []
    permission: essence.gamemode.survival
  gmc:
    description: Switch to creative mode.
    usage: /<command>
    aliases: []
    permission: essence.gamemode.creative
  gma:
    description: Switch to adventure mode.
    usage: /<command>
    aliases: []
    permission: essence.gamemode.adventure
  gmsp:
    description: Switch to spectator mode.
    usage: /<command>
    aliases: []
    permission: essence.gamemode.spectator
  anvil:
    description: Open an anvil.
    usage: /<command>
    aliases: []
    permission: essence.inventory.anvil
  cartography:
    description: Open a cartography table.
    usage: /<command>
    aliases: []
    permission: essence.inventory.cartography
  craft:
    description: Open a crafting table.
    usage: /<command>
    aliases: ['workbench']
    permission: essence.inventory.craft
  enderchest:
    description: Open your ender chest.
    usage: /<command>
    aliases: ['echest']
    permission: essence.inventory.enderchest
  grindstone:
    description: Open a grindstone.
    usage: /<command>
    aliases: []
    permission: essence.inventory.grindstone
  loom:
    description: Open a loom.
    usage: /<command>
    aliases: []
    permission: essence.inventory.loom
  smithing:
    description: Open a smithing table.
    usage: /<command>
    aliases: []
    permission: essence.inventory.smithing
  stonecutter:
    description: Open a stonecutter.
    usage: /<command>
    aliases: []
    permission: essence.inventory.stonecutter
  trash:
    description: Open a disposal menu.
    usage: /<command>
    aliases: ['disposal','garbage']
    permission: essence.inventory.trash
  tp:
    description: Teleport to a player or coordinates.
    usage: /<command> <player> OR /<command> <x> <y> <z>
    aliases: ['teleport']
  warp:
    description: Teleport to a preset warp.
    usage: /<command> <name>
    aliases: []
    permission: essence.warp.use
  warps:
    description: View a list of warps.
    usage: /<command>
    aliases: []
    permission: essence.warp.list
  setwarp:
    description: Create a warp.
    usage: /<command> <name>
    aliases: []
    permission: essence.warp.create
  delwarp:
    description: Delete a warp.
    usage: /<command> <name>
    aliases: []
    permission: essence.warp.delete
  home:
    description: Teleport to a preset home.
    usage: /<command> [name]
    aliases: []
    permission: essence.home.use
  homes:
    description: View a list of homes.
    usage: /<command>
    aliases: []
    permission: essence.home.list
  sethome:
    description: Create a home.
    usage: /<command> <name>
    aliases: []
    permission: essence.home.create
  delhome:
    description: Delete a home.
    usage: /<command> <name>
    aliases: []
    permission: essence.home.delete
  thome:
    description: Teleport to a team home.
    usage: /<command> [name]
    aliases: ['teamhome','ghome','grouphome']
    permission: essence.home.team.use
  thomes:
    description: View a list of team homes.
    usage: /<command>
    aliases: ['teamhomes','ghomes','grouphomes']
    permission: essence.home.team.list
  setthome:
    description: Create a team home.
    usage: /<command> <name>
    aliases: ['setteamhome','setghome','setgrouphome']
    permission: essence.home.team.create
  delthome:
    description: Delete a team home.
    usage: /<command> <name>
    aliases: ['delteamhome','delghome','delgrouphome']
    permission: essence.home.team.delete
  heal:
    description: Heal yourself or someone else.
    usage: /<command> [user]
    aliases: []
    permission: essence.stats.heal
  feed:
    description: Feed yourself or someone else.
    usage: /<command> [user]
    aliases: []
    permission: essence.stats.feed
  broadcast:
    description: Broadcast a message to all online players.
    usage: /<command> <message>
    aliases: []
    permission: essence.chat.broadcast
  back:
    description: Go back to your last location before teleporting.
    usage: /<command>
    aliases: []
    permission: essence.teleport.back
  pay:
    description: Pay someone.
    usage: /<command> <user> <amount>
    aliases: []
    permission: essence.economy.pay
  balance:
    description: See your current balance.
    usage: /<command>
    aliases: ['bal']
    permission: essence.economy.balance
  tprandom:
    description: Teleport to a random location.
    usage: /<command>
    aliases: ['tpr', 'rtp']
    permission: essence.teleport.random
  team:
    description: Manage teams.
    usage: /<command>
    aliases: ['group']
  setspawn:
    description: Set the spawn.
    usage: /<command>
    aliases: ['spawnset']
    permission: essence.spawn.set
  spawn:
    description: Teleport to spawn.
    usage: /<command> [world]
    aliases: ['spawnpoint','world']
    permission: essence.spawn
  repair:
    description: Repair the item in your hand.
    usage: /<command>
    aliases: ['fix']
    permission: essence.stats.repair
  kit:
    description: Get kits.
    usage: /<command>
    aliases: ['kits']
  tpa:
    description: Request to teleport to a player.
    usage: /tpa <user>
    aliases: ['tprequest']
    permission: essence.teleport.request.send
  tpaccept:
    description: Accept a teleportation request.
    usage: /tpaccept
    permission: essence.teleport.request.accept
  tpdeny:
    description: Deny a teleportation request.
    usage: /tpdeny
    aliases: ['tpdecline']
    permission: essence.teleport.request.deny
  tpahere:
    description: Request a player to teleport to you.
    usage: /tpahere
    permission: essence.teleport.request.here
  tptoggle:
    description: Toggle receiving teleport requests.
    usage: /tptoggle
    aliases: ['toggletp']
    permission: essence.teleport.request.toggle
  tpcancel:
    description: Cancel a teleport request.
    usage: /tpcancel
    aliases: ['canceltp']
    permission: essence.teleport.request.cancel
  seen:
    description: See when a player was last online.
    usage: /seen <user>
    aliases: ['pseen','playerseen']
    permission: essence.admin.seen
  info:
    description: See information about a player.
    usage: /info <user>
    aliases: ['pinfo','playerinfo']
    permission: essence.admin.info
  invisible:
    description: Toggles player invisibility.
    usage: /invisible
    aliases: ['visible', 'v']
    permission: essence.admin.invisible
  msg:
    description: Send a private message to another player.
    usage: /msg <user> <message>
    aliases: ['message', 'pm']
    permission: essence.chat.msg
  reply:
    description: Reply to the last private message sent to you.
    usage: /reply <message>
    aliases: ['r']
    permission: essence.chat.reply
  rules:
    description: Displays the server rules.
    usage: /rules
    permission: essence.rules
  nick:
    description: Change your display name.
    usage: /nick
    aliases: ['nickname', 'displayname']
    permission: essence.chat.nick
permissions:
  essence.*:
    description: Access to all essence commands.
    default: op
    children:
      essence.gamemode.*: true
      essence.inventory.*: true
      essence.teleport.*: true
      essence.warp.*: true
      essence.stats.*: true
      essence.stats.other.*: true
      essence.home.*: true
      essence.economy.*: true
      essence.chat.*: true
      essence.playerinfo.*: true
      essence.team.*: true
      essence.spawn.*: true
      essence.kits.*: true
      essence.rules: true
  essence.gamemode.*:
    description: Allows players to switch to any gamemode.
    default: op
    children:
      essence.gamemode.creative: true
      essence.gamemode.survival: true
      essence.gamemode.adventure: true
      essence.gamemode.spectator: true
      essence.gamemode.other: true
  essence.gamemode.creative:
    description: Allows players to switch to creative gamemode.
  essence.gamemode.survival:
    description: Allows players to switch to survival gamemode.
  essence.gamemode.adventure:
    description: Allows players to switch to adventure gamemode.
  essence.gamemode.spectator:
    description: Allows players to switch to spectator gamemode.
  essence.gamemode.other:
    description: Allows you to change other player's gamemodes. You must also have the specific gamemode permission.
  essence.inventory.*:
    description: Allows players to access inventory commands.
    default: op
    children:
      essence.inventory.anvil: true
      essence.inventory.cartography: true
      essence.inventory.craft: true
      essence.inventory.enderchest: true
      essence.inventory.grindstone: true
      essence.inventory.loom: true
      essence.inventory.smithing: true
      essence.inventory.stonecutter: true
      essence.inventory.trash: true
  essence.inventory.anvil:
    description: Allows players to open an anvil when no anvil is present.
  essence.inventory.cartography:
    description: Allows players to open a cartography table when no cartography table is present.
  essence.inventory.craft:
    description: Allows players to open a crafting table when no crafting table is present.
  essence.inventory.enderchest:
    description: Allows players to open their ender chest.
  essence.inventory.grindstone:
    description: Allows players to open a grindstone when no grindstone is present.
  essence.inventory.loom:
    description: Allows players to open a loom when no loom is present.
  essence.inventory.smithing:
    description: Allows players to open a smithing table when no smithing table is present.
  essence.inventory.stonecutter:
    description: Allows players to open a stonecutter when no stonecutter is present.
  essence.inventory.trash:
    description: Allows players to open the disposal menu.
  essence.teleport.*:
    description: Allows players to teleport.
    default: op
    children:
      essence.teleport.coord: true
      essence.teleport.player: true
      essence.teleport.back: true
      essence.teleport.random: true
      essence.teleport.other: true
      essence.teleport.request.*: true
  essence.teleport.coord:
    description: Allows players to teleport to coordinates.
  essence.teleport.player:
    description: Allows players to teleport to a player.
  essence.teleport.back:
    description: Go back to your last location before teleporting.
  essence.teleport.random:
    description: Teleport to a random location.
  essence.teleport.other:
    description: Teleport another player.
  essence.teleport.request.*:
    description: Allow players to request to teleport.
    default: op
    children:
      essence.teleport.request.send: true
      essence.teleport.request.here: true
      essence.teleport.request.accept: true
      essence.teleport.request.deny: true
      essence.teleport.request.toggle: true
      essence.teleport.request.cancel: true
  essence.teleport.request.send:
    description: Request to teleport to a player.
  essence.teleport.request.here:
    description: Request a player teleport to you.
  essence.teleport.request.accept:
    description: Accept a teleport request.
  essence.teleport.request.deny:
    description: Deny a teleport request.
  essence.teleport.request.toggle:
    description: Toggle receiving teleport requests.
  essence.teleport.request.cancel:
    description: Cancel a teleport request.
  essence.warp.*:
    description: Allows players to use and manage warps.
    default: op
    children:
      essence.warp.use: true
      essence.warp.list: true
      essence.warp.create: true
      essence.warp.delete: true
  essence.warp.use:
    description: Allows players to warp.
  essence.warp.list:
    description: Allows players view warps.
  essence.warp.create:
    description: Allows players to create warps.
  essence.warp.delete:
    description: Allows players to delete warps.
  essence.stats.*:
    description: Allows players to manage their stats such as health and hunger.
    default: op
    children:
      essence.stats.heal: true
      essence.stats.feed: true
      essence.stats.repair: true
  essence.stats.heal:
    description: Allows you to heal yourself.
  essence.stats.feed:
    description: Allows you to feed yourself.
  essence.stats.repair:
    description: Allows you to repair items.
  essence.stats.other.*:
    description: Allows players to manage other player's stats such as health and hunger.
    default: op
    children:
      essence.stats.heal.other: true
      essence.stats.feed.other: true
  essence.stats.heal.other:
    description: Allows you to heal other players.
  essence.stats.feed.other:
    description: Allows you to feed other players.
  essence.home.*:
    description: Allows players to use the home system.
    default: op
    children:
      essence.home.list: true
      essence.home.use: true
      essence.home.set: true
      essence.home.delete: true
      essence.home.team.list: true
      essence.home.team.use: true
      essence.home.team.set: true
      essence.home.team.delete: true
  essence.home.list:
    description: View a list of homes.
  essence.home.use:
    description: Allows players to teleport to your homes.
  essence.home.set:
    description: Allows players to set homes.
  essence.home.delete:
    description: Allows players to delete homes.
  essence.home.team.list:
    description: View a list of team homes.
  essence.home.team.use:
    description: Allows players to teleport to team homes.
  essence.home.team.set:
    description: Allows players to set team homes.
  essence.home.team.delete:
    description: Allows players to delete team homes.
  essence.chat.*:
    description: Allows players to use all chat commands.
    default: op
    children:
      essence.chat.broadcast: true
      essence.chat.msg: true
      essence.chat.reply: true
      essence.chat.nick: true
      essence.chat.nick.*: true
  essence.chat.broadcast:
    description: Allows players to broadcast a message to chat.
  essence.chat.msg:
    description: Allows players to privately message.
  essence.chat.reply:
    description: Allows players to change display names.
  essence.chat.nick.*:
    default: op
    children:
      essence.chat.nick.self: true
      essence.chat.nick.other: true
  essence.chat.nick.self:
    description: Allows players to change their display names.
  essence.chat.nick.other:
    description: Allows players to change other player's display names.
  essence.economy.*:
    description: Allows players to access all economy commands.
    default: op
    children:
      essence.economy.pay: true
      essence.economy.balance: true
  essence.economy.pay:
    description: Use /pay command.
  essence.economy.balance:
    description: Use /balance command.
  essence.team.*:
    description: Allows players to access all teams commands.
    default: op
    children:
      essence.team.join: true
      essence.team.create: true
      essence.team.manage: true
      essence.team.list: true
  essence.team.join:
    description: Join a team.
  essence.team.create:
    description: Create a team.
  essence.team.manage:
    description: Manage any teams they are the leader of.
  essence.team.list:
    description: View team information.
  essence.spawn.*:
    description: Allows players to access all spawn commands.
    default: op
    children:
      essence.spawn: true
      essence.spawn.set: true
      essence.spawn.other: true
  essence.spawn.set:
    description: Set the spawn.
  essence.spawn:
    default: not op
    description: Teleport to spawn.
  essence.spawn.other:
    description: Teleport to other world's spawns.
  essence.kits.*:
    description: Allows players to access all kit commands.
    default: op
    children:
      essence.kits.all: true
  essence.kits.all:
    description: Allows players to access all kits.
  essence.admin.*:
    description: Allows players to see information about other players.
    default: op
    children:
      essence.admin.seen: true
      essence.admin.info: true
      essence.admin.reload: true
      essence.admin.import: true
      essence.admin.invisible: true
      essence.admin.updates: true
  essence.admin.seen:
    description: Allows players to see when the player was last online.
  essence.admin.info:
    description: Allows players to see information about the player.
  essence.admin.reload:
    description: Allows players to reload Essence.
  essence.admin.import:
    description: Allows players to reload Essence.
  essence.admin.invisible:
    description: Toggles invisibility.
  essence.admin.updates:
    description: Toggles invisibility.
  essence.bypass.*:
    description: Allows bypassing of various limits.
    default: op
    children:
      essence.bypass.teleportcooldown: true
      essence.bypass.teleportdelay: true
      essence.bypass.maxkitclaims: true
  essence.bypass.teleportcooldown:
    description: Allows bypassing the teleportation cooldown.
  essence.bypass.teleportdelay:
    description: Allows bypassing the teleportation delay.
  essence.bypass.extendedteleporttoggle:
    description: Allows bypassing the extended teleport toggles.
  essence.bypass.maxkitclaims:
    description: Allows bypassing the maximum number of kit redemptions.
  essence.rules:
    description: Allows players to view the server rules.