name: Test Plugin

on:
  push:
    branches:
      - main
      - next-update
  pull_request:
    types:
      - opened
      - reopened
      - review_requested]
    branches:
      - 'main/**'
      - 'next-update/**'

jobs:
  test-server:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        version: [ "1.20.6", "1.21", "1.21.1" ]
        java-version: [21]
        include:
          - version: "1.20.6"
            java-version: 21
          - version: "1.21"
            java-version: 21
          - version: "1.21.1"
            java-version: 21

    name: Minecraft ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Plugin
        run: mvn -B package --file pom.xml
      - name: Bukkit ${{ matrix.version }}
        uses: GamerCoder215/TestMC@v2.0.2
        with:
          path: "/home/runner/work/Essence/Essence/target/essence-*.jar"
          runtime: 'craftbukkit'
          version: ${{ matrix.version }}
          time: 120
          commands: |
            essence
      - name: Spigot ${{ matrix.version }}
        uses: GamerCoder215/TestMC@v2.0.2
        with:
          path: "/home/runner/work/Essence/Essence/target/essence-*.jar"
          runtime: 'spigot'
          version: ${{ matrix.version }}
          time: 120
          commands: |
            essence
      - name: Paper ${{ matrix.version }}
        uses: GamerCoder215/TestMC@v2.0.2
        with:
          path: "/home/runner/work/Essence/Essence/target/essence-*.jar"
          runtime: 'paper'
          version: ${{ matrix.version }}
          time: 120
          commands: |
            essence
      - name: Purpur ${{ matrix.version }}
        uses: GamerCoder215/TestMC@v2.0.2
        with:
          path: "/home/runner/work/Essence/Essence/target/essence-*.jar"
          runtime: 'purpur'
          version: ${{ matrix.version }}
          time: 120
          commands: |
            essence